apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: prepare-release
  labels:
    app: "artcd"
spec:
  params:
  - name: group
    description: Group name. e.g. openshift-4.9
  - name: assembly
    description: The name of an assembly; must be defined in releases.yml (e.g. 4.9.1)
    default: "stream"
  - name: release_name
    description: |-
      A unique identifier for the release. The release name should never change.
      In case of bumping a release with the same content, use ‘override_release_name’.
  - name: release_date
    description: Expected release date
  - name: nightlies
    description: Proposed nightlies for testing and promotion, separated by commas
  - name: package_owner
    description: (Optional) Must be an individual email address; may be anyone who wants random advisory spam
    default: ""
  - name: dry_run
    description: If "true", just exercise the steps without actually preparing a release
    default: "false"
  steps:
  - name: prepare-release
    image: image-registry.openshift-image-registry.svc:5000/art-cd/artcd:latest
    script: |
      #!/usr/bin/env python3
      import logging
      import subprocess
      from pathlib import Path

      subprocess.run(["rm", "-rf", "/root/.ssh"], check=True, universal_newlines=True)
      subprocess.run(["cp", "-r", "/tekton/home/.ssh", "/root/.ssh"], check=True, universal_newlines=True)
      subprocess.run(["chmod", "700", "/root/.ssh"], check=True, universal_newlines=True)
      subprocess.run(["chmod", "600", "/root/.ssh/id_rsa"], check=True, universal_newlines=True)

      Path("./artcd_working").mkdir(parents=True, exist_ok=True)

      subprocess.run(["kinit", "-f", "-k", "-t", "/etc/kerberos-keytab/jenkins-buildvm-keytab", "ocp-build/buildvm.openshift.eng.bos.redhat.com@IPA.REDHAT.COM"], check=True, universal_newlines=True)
      args = [
          "-vv",
          "--working-dir=./artcd_working",
          "--config=/etc/artcd/artcd.toml",
      ]
      if "$(params.dry_run)" == "true":
          args.append("--dry-run")
      args.extend([
          "prepare-release",
          "--group", "$(params.group)",
          "--assembly", "$(params.assembly)",
          "--date", "$(params.release_date)",
      ])
      release_name = "$(params.release_name)"
      if release_name:
          args.extend(["--name", release_name])
      package_owner = "$(params.package_owner)"
      if package_owner:
          args.extend(["--package-owner", package_owner])
      nightlies = [nightly.strip() for nightly in "$(params.nightlies)".split(",") if nightly.strip()]
      for nightly in nightlies:
          args.append("--nightly")
          args.append(nightly)

      print(f"Running artcd {args}...")
      subprocess.run(["artcd"] + args, check=True, universal_newlines=True)

    env:
    - name: JIRA_USERNAME
      valueFrom:
        secretKeyRef:
          name: jira
          key: username
    - name: JIRA_PASSWORD
      valueFrom:
        secretKeyRef:
          name: jira
          key: password
    # https://github.com/tektoncd/pipeline/issues/2013
    - name: HOME
      value: /root
    volumeMounts:
    - name: artcd-config
      mountPath: /etc/artcd/
    - name: elliott-config
      mountPath: /root/.config/elliott/
    - name: doozer-config
      mountPath: /root/.config/doozer/
    - name: ssh-config
      mountPath: /tekton/home/.ssh/known_hosts
      subPath: known_hosts
      readOnly: false
    - name: git-config
      mountPath: /root/.gitconfig
      subPath: .gitconfig
      readOnly: false
    - name: kerberos-config
      mountPath: /etc/krb5.conf.d/krb5-redhat.conf
      subPath: krb5-redhat.conf
    - name: ssh-auth
      mountPath: /tekton/home/.ssh/id_rsa
      subPath: id_rsa
    - name: registry-cred
      mountPath: /root/.docker/config.json
      subPath: .dockerconfigjson
    - name: bugzilla-apikey
      mountPath: /root/.config/python-bugzilla/
    - name: kerberos-keytab
      mountPath: /etc/kerberos-keytab
  volumes:
  - name: artcd-config
    configMap:
      name: artcd-config
  - name: elliott-config
    configMap:
      name: elliott-config
  - name: doozer-config
    configMap:
      name: doozer-config
  - name: ssh-config
    configMap:
      name: ssh-config
  - name: git-config
    configMap:
      name: git-config
  - name: kerberos-config
    configMap:
      name: kerberos-config
  - name: ssh-auth
    secret:
      secretName: artbot-ssh-auth
  - name: registry-cred
    secret:
      secretName: registry-cred
  - name: bugzilla-apikey
    secret:
      secretName: bugzilla-apikey
  - name: kerberos-keytab
    secret:
      secretName: jenkins-buildvm-keytab
