---
provision:
  os: "rhel"
  stage: "base"
  provider: "aws"
sync: []
actions:
  - type: "host_script"
    title: "determine the resource group"
    script: |-
      echo "RESOURCE_GROUP=ci-$JOB_NAME-$BUILD_NUMBER" | ssh -F ./.config/origin-ci-tool/inventory/.ssh_config openshiftdevel "cat >>/etc/environment"

  - type: "script"
    title: "clone repos"
    script: |-
      git clone --branch release-3.9 https://github.com/openshift/openshift-ansible.git
      git clone --branch azure https://github.com/jim-minter/release.git

  - type: "script"
    title: "build openshift installer image"
    script: |-
      cd openshift-ansible
      docker build -f images/installer/Dockerfile -t openshift/origin-ansible:latest .

  - type: "host_script"
    title: "move secrets to remote host"
    script: |-
      rsync --copy-links --omit-dir-times --archive --rsh "ssh -F ./.config/origin-ci-tool/inventory/.ssh_config" /var/lib/jenkins/.azure/* openshiftdevel:/home/origin/release/cluster/test-deploy/azure/
      ssh -F ./.config/origin-ci-tool/inventory/.ssh_config openshiftdevel 'sudo chown -R origin:origin-git /home/origin/release/cluster/test-deploy/azure/'
      ssh -F ./.config/origin-ci-tool/inventory/.ssh_config openshiftdevel 'sudo chmod -R ug+rwX /home/origin/release/cluster/test-deploy/azure/'

  - type: "script"
    title: "build node image"
    script: |-
      cd release/cluster/test-deploy/azure
      TYPE=azure INSTANCE_PREFIX=unused ../../bin/ansible.sh ansible-playbook \
        -e "openshift_azure_resource_group_name=$RESOURCE_GROUP" \
        -e "openshift_azure_resource_location=eastus" \
        -e "openshift_azure_input_image_ns=images" \
        -e "openshift_azure_input_image_prefix=rhel7-base" \
        -e "openshift_azure_output_image_ns=images" \
        -e "openshift_azure_output_image_prefix=rhel7" \
        -e "openshift_azure_storage_account=openshiftimages" \
        -e "openshift_azure_storage_account_ns=images" \
        -e "openshift_azure_container=images" \
        playbooks/azure/openshift-cluster/build_node_image.yml

post_actions:
  - type: "script"
    title: "clean up resources"
    script: |-
      cd release/cluster/test-deploy/azure
      TYPE=azure INSTANCE_PREFIX=unused ../../bin/ansible.sh ansible-playbook \
        -e "openshift_azure_resource_group_name=$RESOURCE_GROUP" \
        playbooks/azure/openshift-cluster/deprovision.yml

email:
- aos-azure@redhat.com
