---
parent: 'common/test_cases/origin_release.yml'
extensions:
  parameters:
    - name: "OS_PUSH_TAG"
      description: "The docker image tag to push to, defaults to :latest"
  sync_repos:
    - name: "origin-web-console-server"
  actions:
    - type: "script"
      title: "create directory for docker config"
      script: |-
        mkdir -p /tmp/.docker
        chmod a+rwx /tmp/.docker
    - type: "host_script"
      title: "transfer docker config to remote host"
      script: |-
        scp -F ./.config/origin-ci-tool/inventory/.ssh_config /var/lib/jenkins/.docker/config.json openshiftdevel:/tmp/.docker/
    - type: "forward_parameters"
      parameters:
        - OS_PUSH_TAG
    - type: "script"
      title: "push the release"
      repository: "origin"
      script: |-
        sudo chmod a+rw /tmp/.docker/config.json
        DOCKER_CONFIG=/tmp/.docker OS_PUSH_LOCAL=1 OS_PUSH_ALWAYS=1 OS_PUSH_BASE_REGISTRY="docker.io/" hack/push-release.sh
    - type: "script"
      title: "build an image registry release"
      repository: "image-registry"
      script: |-
        make build-images
    - type: "script"
      title: "build a kubernetes metrics server release"
      repository: "kubernetes-metrics-server"
      script: |-
        make build-images
    - type: "script"
      title: "push the image registry release"
      repository: "image-registry"
      script: |-
        DOCKER_CONFIG=/tmp/.docker OS_PUSH_LOCAL=1 OS_PUSH_ALWAYS=1 OS_PUSH_BASE_REGISTRY="docker.io/" hack/push-release.sh
    - type: "script"
      title: "push the image registry release"
      repository: "kubernetes-metrics-server"
      script: |-
        DOCKER_CONFIG=/tmp/.docker OS_PUSH_LOCAL=1 OS_PUSH_ALWAYS=1 OS_PUSH_BASE_REGISTRY="docker.io/" hack/push-release.sh
    - type: "script"
      title: "build a web console release"
      repository: "origin-web-console-server"
      script: |-
        make build-images
    - type: "script"
      title: "push the web console release"
      repository: "origin-web-console-server"
      script: |-
        DOCKER_CONFIG=/tmp/.docker OS_PUSH_LOCAL=1 OS_PUSH_ALWAYS=1 OS_PUSH_BASE_REGISTRY="docker.io/" hack/push-release.sh        
        sudo rm -rf /tmp/.docker