---
parent: 'common/test_cases/origin_release_install_gce.yml'
overrides:
  junit_analysis: False
  sync_repos:
    - name: "origin"
      type: "pull_request"
    - name: "openshift-ansible"
    - name: "aos-cd-jobs"
    - name: "image-registry"
    - name: "kubernetes-metrics-server"
    - name: "release"
extensions:
  parameters:
    - name: "SUITE"
      description: "Which shell file in the <a href='https://github.com/openshift/origin/tree/master/test/extended'><code>origin/test/extended/</code></a> di
rectory to run."
      default_value: "conformance"
