---
parent: 'common/test_cases/origin_release_with_ecosystem_310.yml'
overrides:
  junit_analysis: False
extensions:
  actions:
    - type: "script"
      title: "run extended tests"
      repository: "origin"
      script: |-
        OPENSHIFT_SKIP_BUILD='true' JUNIT_REPORT='true' make test-extended SUITE=gssapi
