---
parent: 'common/test_cases/origin_built_installed_release_310.yml'
overrides:
  sync:
    - "openshift,aos-cd-jobs=master"
    - "openshift,image-registry=release-3.10"
    - "openshift,openshift-ansible=release-3.10"
    - "openshift,kubernetes-metrics-server=release-3.10"
    - "openshift,origin-web-console-server=release-3.10"
  evars: "-e openshift_use_system_containers=true -e openshift_docker_systemcontainer_image_registry_override=brew-pulp-docker01.web.prod.ext.phx2.redhat.com:8888/rhel7 -e system_images_registry=docker -e containerized=true"
extensions:
  parameters:
    - name: "OSTREE_COPY"
      default: "true"
  actions:
    - type: "script"
      title: "run extended tests"
      repository: "origin"
      script: |-
        OS_BUILD_ENV_PULL_IMAGE=true OS_BUILD_ENV_PRESERVE=_output/local/bin/linux/amd64/extended.test hack/env make build-extended-test
        # configure dnsmasq to forward requests to openhsift's DNS
        cat <<HEREDOC > ci-dnsmasq.conf
        server=/local/127.0.0.1#8053
        server=/17.30.172.in-addr.arpa/127.0.0.1#8053
        HEREDOC
        sudo cp ci-dnsmasq.conf /etc/dnsmasq.d/ci-dnsmasq.conf
        sudo systemctl restart dnsmasq
        sudo systemctl status dnsmasq
        # run the tests with fingers crossed
        #OPENSHIFT_SKIP_BUILD='true' KUBECONFIG=/etc/origin/master/admin.kubeconfig TEST_ONLY='true' JUNIT_REPORT='true' SUITE=conformance make test-extended TEST_EXTENDED_ARGS="-ginkgo.skip=should\sanswer\sendpoint\sand\swildcard\squeries\sfor\sthe\scluster|should\sprovide\sDNS\sfor\spods\sfor\sHostname\sand\sSubdomain\sAnnotation|should\sprovide\sDNS\sfor\sservices|should\sprovide\sDNS\sfor\sthe\scluster|should\sexpose\sthe\sprofiling\sendpoints"
