---
parent: 'test_cases/test_branch_origin_extended_conformance_install_310.yml'
overrides:
  junit_analysis: True
  sync:
    - "openshift,origin=release-3.10"
    - "openshift,aos-cd-jobs=release-3.10"
    - "openshift,image-registry=release-3.10"
    - "openshift,kubernetes-metrics-server=release-3.10"
    - "openshift,origin-web-console-server=release-3.10"
