---
parent: 'test_cases/test_pull_request_origin_aggregated_logging_journald.yml'
overrides:
  sync:
    - "openshift,origin=release-3.7"
    - "openshift,aos-cd-jobs=master"
    - "openshift,openshift-ansible=release-3.7"
