---
parent: 'common/test_cases/origin_release.yml'
extensions:
  actions:
    - type: "script"
      title: "build an openshift-ansible release"
      repository: "openshift-ansible"
      script: |-
        tito_tmp_dir="tito"
        mkdir -p "${tito_tmp_dir}"
        tito tag --offline --accept-auto-changelog --use-release 9999
        tito build --output="${tito_tmp_dir}" --rpm --test --offline --quiet
        createrepo "${tito_tmp_dir}/noarch"
        cat << EOR > ./openshift-ansible-local-release.repo
        [openshift-ansible-local-release]
        baseurl = file://$( pwd )/${tito_tmp_dir}/noarch
        gpgcheck = 0
        name = OpenShift Ansible Release from Local Source
        EOR
        sudo cp ./openshift-ansible-local-release.repo /etc/yum.repos.d
    - type: "script"
      title: "determine the release commit for origin images and version for rpms"
      repository: "origin"
      script: |-
        registry_repo="/data/src/github.com/openshift/image-registry/"
        git log -1 --pretty=%h >> "${registry_repo}/ORIGIN_COMMIT"
        console_repo="/data/src/github.com/openshift/origin-web-console-server/"
        git log -1 --pretty=%h >> "${console_repo}/ORIGIN_COMMIT"
    - type: "script"
      title: "build the image registry container image"
      repository: "image-registry"
      timeout: 3600
      script: |-
        make build-images
        docker tag openshift/origin-docker-registry:latest "openshift/origin-docker-registry:$( cat ./ORIGIN_COMMIT )"
    - type: "script"
      title: "build the origin web console server container image"
      repository: "origin-web-console-server"
      timeout: 3600
      script: |-
        make build-images
        docker tag openshift/origin-web-console:latest "openshift/origin-web-console:$( cat ./ORIGIN_COMMIT )"
