---
parent: 'common/test_cases/origin_release.yml'
extensions:
  sync:
    - "openshift,image-registry=master"
    - "openshift,kubernetes-metrics-server=master"
    - "openshift,origin-web-console-server=master"
  actions:
    - type: "script"
      title: "determine the release commit for origin images and version for rpms"
      repository: "origin"
      script: |-
        registry_repo="/data/src/github.com/openshift/image-registry/"
        git log -1 --pretty=%h >> "${registry_repo}/ORIGIN_COMMIT"
        metrics_repo="/data/src/github.com/openshift/kubernetes-metrics-server/"
        git log -1 --pretty=%h >> "${metrics_repo}/ORIGIN_COMMIT"
        console_repo="/data/src/github.com/openshift/origin-web-console-server/"
        git log -1 --pretty=%h >> "${console_repo}/ORIGIN_COMMIT"
    - type: "script"
      title: "build the image registry container image"
      repository: "image-registry"
      timeout: 3600
      script: |-
        if [[ "${PULL_BASE_REF}" == "master" || "${PULL_BASE_REF}" == "release-3.7" || "${PULL_BASE_REF}" == "release-3.8" || "${PULL_BASE_REF}" == "release-3.9" ]]; then
          make build-images
          docker tag openshift/origin-docker-registry:latest "openshift/origin-docker-registry:$( cat ./ORIGIN_COMMIT )"
        fi
    - type: "script"
      title: "build the kubernetes metrics server container image"
      repository: "kubernetes-metrics-server"
      timeout: 3600
      script: |-
        if [[ "${PULL_BASE_REF}" == "master" || "${PULL_BASE_REF}" == "release-3.9" ]]; then
          make build-images
          docker tag openshift/origin-metrics-server:latest "openshift/origin-metrics-server:$( cat ./ORIGIN_COMMIT )"
        fi
    - type: "script"
      title: "build the origin web console server container image"
      repository: "origin-web-console-server"
      timeout: 3600
      script: |-
        if [[ "${PULL_BASE_REF}" == "master" || "${PULL_BASE_REF}" == "release-3.9" ]]; then
          make build-images
          docker tag openshift/origin-web-console:latest "openshift/origin-web-console:$( cat ./ORIGIN_COMMIT )"
        fi
